import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// The same tokens feed the site, widget Shadow DOM, plots, and diagram template.
const root = new URL('../', import.meta.url);
const tokens = JSON.parse(readFileSync(new URL('assets/styles/tokens.json', root), 'utf8'));
const { colors, fonts, typography } = tokens;
const variables = Object.entries(colors).map(([name, value]) => `  --infra-${name.replaceAll('_', '-')}: ${value};`).join('\n');

const css = `/* Generated by npm run style. Edit assets/styles/tokens.json or scripts/build-style.mjs. */
:root, :host {
${variables}
  --infra-font-body: ${fonts.body};
  --infra-font-code: ${fonts.code};
}
body { background: var(--infra-background); font-family: var(--infra-font-body); }
main { background: var(--infra-background); }
.prose { color: var(--infra-text); font-family: var(--infra-font-body); font-size: ${typography.body_px}px; line-height: ${typography.line_height}; }
.prose :is(h1, h2, h3, h4, strong) { color: var(--infra-text); }
.prose a { color: var(--infra-communication); text-underline-offset: .2em; }
.prose :is(code, pre) { font-family: var(--infra-font-code); }
.prose blockquote { color: var(--infra-muted); border-left-color: var(--infra-communication); }
.prose :is(th, td) { border-color: var(--infra-border); }
.prose th { background: var(--infra-communication-fill); }
.prose figure { margin: 1.8em 0; }
.prose figcaption { color: var(--infra-muted); font-size: .88em; }

.infra-widget { background: var(--infra-surface); color: var(--infra-text); font-family: var(--infra-font-body); border: 1px solid var(--infra-border); border-radius: 14px; padding: 20px; }
.infra-widget * { box-sizing: border-box; }
.infra-widget h3 { margin: 0 0 8px; font-size: 20px; }
.infra-widget p { line-height: 1.6; }
.infra-widget .model-note { margin: 0 0 20px; color: var(--infra-muted); font-size: 14px; }
.infra-widget .controls { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 20px; }
.infra-widget label { display: flex; flex-direction: column; gap: 8px; font-size: 14px; }
.infra-widget input { width: 100%; accent-color: var(--infra-communication); }
.infra-widget output { font-family: var(--infra-font-code); font-size: 13px; }
.infra-widget .summary { padding: 12px 0 0; font-size: 15px; }
.infra-widget svg { display: block; width: 100%; height: auto; margin-top: 12px; }
.infra-widget svg text { fill: var(--infra-muted); font-size: 12px; font-family: var(--infra-font-body); }
.infra-widget .grid-line { stroke: var(--infra-border); stroke-width: 1; stroke-dasharray: 3 5; }
.infra-widget .axis { stroke: var(--infra-muted); stroke-width: 1; }
.infra-widget .compute-line { stroke: var(--infra-compute); stroke-width: 2; stroke-dasharray: 6 5; fill: none; }
.infra-widget .memory-line { stroke: var(--infra-memory); stroke-width: 2; fill: none; }
.infra-widget .bound-line { stroke: var(--infra-communication); stroke-width: 3; fill: none; }
.infra-widget .workload { fill: var(--infra-warning); stroke: var(--infra-surface); stroke-width: 2; }
.infra-widget .legend { display: flex; flex-wrap: wrap; gap: 16px; font-size: 13px; }
.infra-widget .legend span::before { content: ''; display: inline-block; width: 16px; height: 3px; margin: 0 6px 3px 0; background: var(--infra-communication); }
.infra-widget .legend .compute::before { background: var(--infra-compute); }
.infra-widget .legend .memory::before { background: var(--infra-memory); }
@media (max-width: 560px) { .infra-widget { padding: 14px; } .infra-widget .controls { grid-template-columns: 1fr; gap: 14px; } }
`;
writeFileSync(new URL('assets/styles/site.css', root), css);

// mplstyle treats # as a comment; Matplotlib accepts unprefixed hex colors.
const hex = (name) => colors[name].slice(1);
const mpl = `# Generated by npm run style. Edit tokens.json or build-style.mjs.
font.family: ${fonts.plot}
font.size: ${typography.plot_pt}
axes.titlesize: 13
axes.labelsize: ${typography.plot_pt}
legend.fontsize: 10
xtick.labelsize: 10
ytick.labelsize: 10
figure.figsize: 7.2, 4.2
figure.dpi: 120
figure.facecolor: ${hex('background')}
axes.facecolor: ${hex('surface')}
savefig.facecolor: ${hex('background')}
text.color: ${hex('text')}
axes.labelcolor: ${hex('text')}
axes.edgecolor: ${hex('muted')}
xtick.color: ${hex('muted')}
ytick.color: ${hex('muted')}
axes.prop_cycle: cycler('color', ['${hex('compute')}', '${hex('memory')}', '${hex('communication')}', '${hex('warning')}'])
axes.spines.top: False
axes.spines.right: False
axes.grid: True
axes.axisbelow: True
grid.color: ${hex('border')}
grid.alpha: 0.6
grid.linewidth: 0.6
lines.linewidth: 1.8
lines.markersize: 5
figure.constrained_layout.use: True
savefig.dpi: 180
svg.fonttype: path
pdf.fonttype: 42
`;
writeFileSync(new URL('assets/styles/plots.mplstyle', root), mpl);

const diagram = `<!-- Generated by npm run style. Copy the block and replace nodes for a new diagram. -->
\`\`\`mermaid
---
config:
  theme: base
  themeVariables:
    background: '${colors.background}'
    primaryColor: '${colors.communication_fill}'
    primaryTextColor: '${colors.text}'
    primaryBorderColor: '${colors.communication}'
    lineColor: '${colors.muted}'
    fontFamily: 'system-ui, sans-serif'
---
flowchart LR
    input[Input buffers]:::memory --> transfer[Data movement]:::communication
    transfer --> compute[Vector addition]:::compute
    compute --> output[Output buffer]:::memory
    classDef compute fill:${colors.compute_fill},stroke:${colors.compute},color:${colors.text}
    classDef memory fill:${colors.memory_fill},stroke:${colors.memory},color:${colors.text}
    classDef communication fill:${colors.communication_fill},stroke:${colors.communication},color:${colors.text}
    classDef warning fill:${colors.warning_fill},stroke:${colors.warning},color:${colors.text}
\`\`\`
`;
writeFileSync(new URL('templates/diagram.md', root), diagram);
console.log(`Updated site, plot, and diagram styles in ${fileURLToPath(root)}`);
